create table if not exists public.financeiro_base_importada (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  arquivo_origem text,
  ano integer,
  cenario text not null,
  periodo integer,
  centro_custo text,
  conta_razao text,
  numero_documento text,
  elemento_pep text,
  valor numeric(18,2) not null default 0,
  area_funcional text,
  texto text,
  documento_compras text,
  material_descricao text,
  descricao_cc text,
  analytical_nature text,
  sub_categorization text,
  category text,
  diretoria text,
  budget_owner text,
  hfm_line text,
  comentarios_controladoria text,
  le text
);

create index if not exists idx_financeiro_base_ano
  on public.financeiro_base_importada (ano);

create index if not exists idx_financeiro_base_cenario
  on public.financeiro_base_importada (cenario);

create index if not exists idx_financeiro_base_periodo
  on public.financeiro_base_importada (periodo);

create index if not exists idx_financeiro_base_category
  on public.financeiro_base_importada (category);

create index if not exists idx_financeiro_base_hfm_line
  on public.financeiro_base_importada (hfm_line);

create or replace view public.vw_financeiro_categoria_mes as
select
  coalesce(ano, 2026) as ano,
  cenario,
  periodo,
  coalesce(category, 'Sem categoria') as categoria,
  coalesce(sub_categorization, 'Sem subcategoria') as subcategoria,
  coalesce(analytical_nature, 'Sem natureza') as natureza_analitica,
  coalesce(hfm_line, 'Sem linha HFM') as hfm_line,
  sum(valor) as valor_total
from public.financeiro_base_importada
group by
  coalesce(ano, 2026),
  cenario,
  periodo,
  coalesce(category, 'Sem categoria'),
  coalesce(sub_categorization, 'Sem subcategoria'),
  coalesce(analytical_nature, 'Sem natureza'),
  coalesce(hfm_line, 'Sem linha HFM');

create or replace view public.vw_financeiro_cenario_mes as
select
  coalesce(ano, 2026) as ano,
  periodo,
  cenario,
  sum(valor) as valor_total
from public.financeiro_base_importada
group by
  coalesce(ano, 2026),
  periodo,
  cenario;

create or replace view public.vw_financeiro_variacao as
with base as (
  select
    coalesce(ano, 2026) as ano,
    periodo,
    coalesce(category, 'Sem categoria') as categoria,
    cenario,
    sum(valor) as valor_total
  from public.financeiro_base_importada
  group by
    coalesce(ano, 2026),
    periodo,
    coalesce(category, 'Sem categoria'),
    cenario
)
select
  b1.ano,
  b1.periodo,
  b1.categoria,
  b1.cenario as cenario_base,
  b2.cenario as cenario_comparativo,
  b1.valor_total as valor_base,
  b2.valor_total as valor_comparativo,
  (b2.valor_total - b1.valor_total) as variacao_valor,
  case
    when b1.valor_total = 0 then null
    else round(((b2.valor_total - b1.valor_total) / b1.valor_total) * 100, 2)
  end as variacao_percentual
from base b1
join base b2
  on b1.ano = b2.ano
 and b1.periodo = b2.periodo
 and b1.categoria = b2.categoria
 and b1.cenario <> b2.cenario;

alter table public.financeiro_base_importada enable row level security;

drop policy if exists "financeiro_base_importada_select" on public.financeiro_base_importada;
create policy "financeiro_base_importada_select"
on public.financeiro_base_importada
for select
to anon, authenticated
using (true);

drop policy if exists "financeiro_base_importada_insert" on public.financeiro_base_importada;
create policy "financeiro_base_importada_insert"
on public.financeiro_base_importada
for insert
to anon, authenticated
with check (true);

drop policy if exists "financeiro_base_importada_delete" on public.financeiro_base_importada;
create policy "financeiro_base_importada_delete"
on public.financeiro_base_importada
for delete
to anon, authenticated
using (true);
